//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v4

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CDBPass) DeepCopyInto(out *CDBPass) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CDBPass.
func (in *CDBPass) DeepCopy() *CDBPass {
	if in == nil {
		return nil
	}
	out := new(CDBPass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CDBSys) DeepCopyInto(out *CDBSys) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CDBSys.
func (in *CDBSys) DeepCopy() *CDBSys {
	if in == nil {
		return nil
	}
	out := new(CDBSys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDB) DeepCopyInto(out *PDB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDB.
func (in *PDB) DeepCopy() *PDB {
	if in == nil {
		return nil
	}
	out := new(PDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PDB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBList) DeepCopyInto(out *PDBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PDB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBList.
func (in *PDBList) DeepCopy() *PDBList {
	if in == nil {
		return nil
	}
	out := new(PDBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PDBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBPass) DeepCopyInto(out *PDBPass) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBPass.
func (in *PDBPass) DeepCopy() *PDBPass {
	if in == nil {
		return nil
	}
	out := new(PDBPass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBSecret) DeepCopyInto(out *PDBSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBSecret.
func (in *PDBSecret) DeepCopy() *PDBSecret {
	if in == nil {
		return nil
	}
	out := new(PDBSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBSpec) DeepCopyInto(out *PDBSpec) {
	*out = *in
	out.CBDsys = in.CBDsys
	out.CBDpwd = in.CBDpwd
	out.Pdbuser = in.Pdbuser
	out.Pdbpass = in.Pdbpass
	if in.ReuseTempFile != nil {
		in, out := &in.ReuseTempFile, &out.ReuseTempFile
		*out = new(bool)
		**out = **in
	}
	if in.UnlimitedStorage != nil {
		in, out := &in.UnlimitedStorage, &out.UnlimitedStorage
		*out = new(bool)
		**out = **in
	}
	if in.AsClone != nil {
		in, out := &in.AsClone, &out.AsClone
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBSpec.
func (in *PDBSpec) DeepCopy() *PDBSpec {
	if in == nil {
		return nil
	}
	out := new(PDBSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBStatus) DeepCopyInto(out *PDBStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBStatus.
func (in *PDBStatus) DeepCopy() *PDBStatus {
	if in == nil {
		return nil
	}
	out := new(PDBStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBsys) DeepCopyInto(out *PDBsys) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBsys.
func (in *PDBsys) DeepCopy() *PDBsys {
	if in == nil {
		return nil
	}
	out := new(PDBsys)
	in.DeepCopyInto(out)
	return out
}
