# This rule is not used by the project pdboperator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the database.oracle.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pdboperator
    app.kubernetes.io/managed-by: kustomize
  name: pdb-editor-role
rules:
- apiGroups:
  - database.oracle.com
  resources:
  - pdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.oracle.com
  resources:
  - pdbs/status
  verbs:
  - get
