apiVersion: database.oracle.com/v4
kind: PDB
metadata:
  name: pdb1
  namespace: pdbnamespace 
spec:
  pdbName: pdb1_tnt
  tnsstring: (DESCRIPTION=(CONNECT_TIMEOUT=90)(RETRY_COUNT=30)(RETRY_DELAY=10)(TRANSPORT_CONNECT_TIMEOUT=70)(TRANSPORT_CONNECT_TIMEOUT=10)(LOAD_BALLANCE=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=phoenix416171.dev3sub2phx.databasede3phx.oraclevcn.com)(PORT=1521)(IP=V4_ONLY))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=c4.regress.rdbms.dev.us.oracle.com)))
  totalSize: "2G"
  tempSize: "800M"
  fileNameConversions: "'.....path1.....','pdb1_tnt'"
  reuseTempFile: true
  unlimitedStorage: true
  cdbSys:
    secret:
      secretName: "syssecret"
      key: "sysusr"
  cdbPwd:
    secret:
      secretName: "syssecret"
      key: "syspwd"
  pdbSys:
    secret:
      secretName: "pdbsecret"
      key: "sysusr"
  pdbPwd:
    secret:
      secretName: "pdbsecret"
      key: "syspwd"
