apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pdboperator-pdboperator-manager-rolebinding1
  namespace: pdbnamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pdboperator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: pdboperator-system
